# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    Python27:
      python.version: '2.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    apt-get update 
    apt-get install sudo 
    sudo apt-get -y upgrade 
    sudo apt-get -y install pkg-config 
    sudo apt-get -y -f install scons git gcc libsndio-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev libgtk-3-dev 
    scons -v 
  displayName: 'Install dependencies'

- script: |
    scons -j8
  displayName: 'Build target'

