import os

env=DefaultEnvironment().Clone();
BIN_DIR=os.environ['BIN_DIR'];
LIB_DIR=os.environ['LIB_DIR'];
CPPPATH = os.environ['LIB_DIR'];
env['CPPPATH'] = ['lib'] + env['CPPPATH']

env.Library(os.path.join(LIB_DIR, 'qrencode'), Glob('lib/qrencode/*.c'));
env.Library(os.path.join(LIB_DIR, 'awtk_qr'), Glob('qr/*.c'));

env['LIBS'] = ['qrencode'] + env['LIBS']
env['LIBS'] = ['awtk_qr'] + env['LIBS']
env['LINKFLAGS'] = env['OS_SUBSYSTEM_WINDOWS'] + env['LINKFLAGS'];
